/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/animatedShip.glb 
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame, useLoader } from '@react-three/fiber'
import * as THREE from 'three'
import { Water } from 'three-stdlib'

function OceanShader({ position, scale }) {
  const ref = useRef()
  const waterNormals = useLoader(THREE.TextureLoader, '/textures/waternormals.jpg')
  waterNormals.wrapS = waterNormals.wrapT = THREE.RepeatWrapping

  const waterGeo = useMemo(() => new THREE.PlaneGeometry(1000, 1000), [])
  const water = useMemo(() => new Water(
    waterGeo,
    {
      textureWidth: 512,
      textureHeight: 512,
      waterNormals,
      sunDirection: new THREE.Vector3(),
      sunColor: 0xffffff,
      waterColor: 0x001e0f,
      distortionScale: 3.7,
      fog: false,
    }
  ), [waterNormals, waterGeo])

  useFrame((state, delta) => {
    water.material.uniforms.time.value += delta * 0.5
  })

  return (
    <group position={position}>
      <primitive object={water} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}


export function AnimatedShip(props) {
  const { nodes, materials } = useGLTF('/models/animatedShip.glb')
  const shipGroupRef = useRef()

  useFrame((state) => {
    const t = state.clock.getElapsedTime()
    if (shipGroupRef.current) {
      // Subtle but slightly faster rocking on X and Z axes
      shipGroupRef.current.rotation.z = Math.sin(t * 1.0) * 0.015
      shipGroupRef.current.rotation.x = Math.cos(t * 0.8) * 0.01
      // Subtle vertical bobbing
      shipGroupRef.current.position.y = Math.sin(t * 1.2) * 0.04
    }
  })

  return (
    <group {...props} dispose={null}>
      <group ref={shipGroupRef}>
        <group position={[0, 4, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={4.689}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Standardmaterial} position={[-0.189, -1.015, -0.012]} rotation={[-3.122, 0, -3.133]} />
          </group>
        </group>
      </group>
      <OceanShader position={[0, -0.2, 0]} />
    </group>
  )
}

useGLTF.preload('/models/animatedShip.glb')
