/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/technology.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Technology(props) {
    const { nodes, materials } = useGLTF('/models/technology.glb')
    return (
        <group {...props} dispose={null}>
            <mesh geometry={nodes.Plane_Material001_0.geometry} material={materials.Poliigon_MetalGoldPaint_7253_512} />
            <mesh geometry={nodes.Plane_Material001_0001.geometry} material={materials.Poliigon_MetalGoldPaint_7253_512} />
            <mesh geometry={nodes.Plane_Material001_0002.geometry} material={materials.Poliigon_MetalGoldPaint_7253_512} />
            <mesh geometry={nodes.Plane_Material001_0003.geometry} material={materials.Poliigon_MetalGoldPaint_7253_512} />
            <mesh geometry={nodes.Plane_Material001_0004.geometry} material={materials.Poliigon_MetalGoldPaint_7253_512} />
        </group>
    )
}

useGLTF.preload('/models/technology.glb')
