/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/scroll.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Scroll(props) {
    const { nodes, materials } = useGLTF('/models/scroll.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, Math.PI / 0.57]} scale={0.006}>
                <group rotation={[Math.PI / 2, 0, 0]}>
                    <mesh geometry={nodes.Stand__0.geometry} material={materials['Scene_-_Root']} position={[-0.11, 48.532, 1.066]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={1} />
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/scroll.glb')
