/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/gallery.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Gallery(props) {
    const { nodes, materials } = useGLTF('/models/gallery.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0, 1, 0]}>
                <mesh geometry={nodes.Object_25.geometry} material={materials.Wall} />
                <mesh geometry={nodes.Object_26.geometry} material={materials['Material.001']} />
            </group>
            <group position={[11.756, 0.312, -1.447]}>
                <mesh geometry={nodes.Object_21.geometry} material={materials.Wall} />
                <mesh geometry={nodes.Object_22.geometry} material={materials.Light} />
                <mesh geometry={nodes.Object_23.geometry} material={materials['Material.001']} />
            </group>
            <group position={[16.207, 3.556, -2.954]} rotation={[-1.996, -0.554, -2.281]}>
                <mesh geometry={nodes.Object_12.geometry} material={materials.light_Plastic} />
                <mesh geometry={nodes.Object_13.geometry} material={materials.Light} />
            </group>
            <group position={[10.887, 3.827, -5.31]}>
                <mesh geometry={nodes.Object_10.geometry} material={materials.light_Plastic} />
                <mesh geometry={nodes.Object_9.geometry} material={materials.Light} />
            </group>
            <group position={[5.006, 1.513, 6.456]}>
                <mesh geometry={nodes.Object_4.geometry} material={materials.frame} />
                <mesh geometry={nodes.Object_5.geometry} material={materials.Glass} />
                <mesh geometry={nodes.Object_6.geometry} material={materials.Wall} />
                <mesh geometry={nodes.Object_7.geometry} material={materials['Material.001']} />
            </group>
            <mesh geometry={nodes.Object_19.geometry} material={materials.Floor} position={[0, 1, 0]} />
            <mesh geometry={nodes.Object_17.geometry} material={materials.frame} position={[0, 1, 0]} />
            <mesh geometry={nodes.Object_15.geometry} material={materials.Glass} position={[0, 1, 0]} />
        </group>
    )
}

useGLTF.preload('/models/gallery.glb')
