/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chess.glb 
*/

import React, { useRef, useEffect } from 'react'
import { useGLTF } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'
import ScrollTrigger from 'gsap/ScrollTrigger'
import { usePathname } from 'next/navigation'

gsap.registerPlugin(ScrollTrigger)

export function Chess(props) {
    const pathname = usePathname();
    const { nodes, materials } = useGLTF('/models/chess.glb')

    const whiteQueensPawnRef = useRef()
    const whiteBishopsPawnRef = useRef()
    const blackKingsPawnRef = useRef()
    const blackBishopRef = useRef()
    const blackBishopRef2 = useRef()
    const blackBishopRef3 = useRef()
    const blackBishopRef4 = useRef()
    const whiteBishopRef = useRef()
    const whiteBishopRef2 = useRef()
    const whiteQueenRef = useRef()
    const whiteQueenRef2 = useRef()
    const blackQueenRef = useRef()

    useEffect(() => {
        Object.values(materials).forEach((material) => {
            material.metalness = 0.8
            material.roughness = 0.15
            material.needsUpdate = true
        })
    }, [materials])

    useGSAP(() => {
        if (pathname !== '/mainScene') return;

        const timeline = gsap.timeline({
            scrollTrigger: {
                trigger: "body",
                start: "top top", // Jedan jedini glavi ScrollTrigger
                end: "bottom bottom",
                scrub: true,
            }
        });

        // Inicijalizujemo timeline od 10 "sekundi" = 100% visine skrola
        timeline.to({}, { duration: 10 });

        // 11% - 15% (Start na 1.1, traje 0.4)
        timeline.to(whiteQueensPawnRef.current.position, {
            x: 0, y: 0, z: -4.1,
            duration: 0.4,
        }, 1.3);

        // 18% - 21% (Start na 1.8, traje 0.3)
        timeline.to(blackKingsPawnRef.current.position, {
            x: 0, y: 0, z: 4.1,
            duration: 0.3,
        }, 1.8);

        // 31% - 35% (Start na 3.1, traje 0.4)
        timeline.to(whiteBishopsPawnRef.current.position, {
            x: 0, y: 0, z: -4.1,
            duration: 0.4,
        }, 3.1);

        // 41% - 45% (Start na 4.1, traje 0.4)
        timeline.to(blackBishopRef.current.position, {
            x: -7.85, y: 0, z: 8,
            duration: 0.4,
        }, 4.1);

        // 51% - 55% (Start na 5.1, traje 0.4)
        timeline.to(whiteBishopRef.current.position, {
            x: 2, y: 0, z: -1.9,
            duration: 0.4,
        }, 5.1);

        // 61% - 63% (Start na 6.1, traje 0.2)
        timeline.to(blackBishopRef2.current.position, {
            x: 2.8, y: 0, z: 2.8,
            duration: 0.2,
        }, 6.1);

        // 64% - 66% (Start na 6.4, traje 0.2)
        timeline.to(whiteBishopRef2.current.position, {
            x: -2, z: 1, duration: 0.1, // prvi deo animacije
        }, 6.4)
            .to(whiteBishopRef2.current.position, {
                z: 10, duration: 0.1,       // drugi deo animacije
            }, 6.5);

        // 66% - 68% (Start na 6.6, traje 0.2)
        timeline.to(blackBishopRef3.current.position, {
            x: 1, y: 0, z: 1.2,
            duration: 0.2,
        }, 6.6);

        // 68% - 70% (Start na 6.8, traje 0.2)
        timeline.to(whiteQueenRef.current.position, {
            x: 0, y: 0, z: -0.35,
            duration: 0.2,
        }, 6.8);

        // 70% - 74% (Start na 7.0, traje 0.4)
        timeline.to(blackBishopRef4.current.position, {
            x: -2, z: 1, duration: 0.2,
        }, 7.0)
            .to(blackBishopRef4.current.position, {
                z: 10, duration: 0.2,
            }, 7.2);

        // 72.5% - 74.5% (Start na 7.25, traje 0.2)
        timeline.to(whiteQueenRef2.current.position, {
            x: -0.1, y: 0, z: -1.53,
            duration: 0.2,
        }, 7.25);

        // 81% - 85% (Start na 8.1, traje 0.4)
        timeline.to(blackQueenRef.current.position, {
            x: 4, y: 0, z: 4,
            duration: 0.4,
        }, 8.3);

        return () => {
            timeline.scrollTrigger?.kill();
            timeline.kill();
        };

    }, [pathname]);






    return (
        <group {...props} dispose={null}>
            <group position={[0, -0.417, 0]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_10.geometry} material={materials['Material.006']} />
                <mesh castShadow receiveShadow geometry={nodes.Object_11.geometry} material={materials['Material.007']} />
                <mesh castShadow receiveShadow geometry={nodes.Object_9.geometry} material={materials['Material.004']} />
            </group>
            <group position={[0, 0.01, 0]} scale={[7.939, 46.607, 7.939]}>
                <mesh castShadow receiveShadow geometry={nodes.Object_6.geometry} material={materials['Material.002']} />
                <mesh castShadow receiveShadow geometry={nodes.Object_7.geometry} material={materials['Material.003']} />
            </group>
            <group ref={blackQueenRef}>
                <mesh castShadow receiveShadow geometry={nodes.Object_41.geometry} material={materials['Material.005']} position={[-1.044, 1.509, -7.028]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
                <mesh castShadow receiveShadow geometry={nodes.Object_43.geometry} material={materials['Material.005']} position={[-1.044, 2.826, -7.028]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
                <mesh castShadow receiveShadow geometry={nodes.Object_45.geometry} material={materials['Material.005']} position={[-1.044, 3.012, -7.028]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
                <mesh castShadow receiveShadow geometry={nodes.Object_47.geometry} material={materials['Material.005']} position={[-1.044, 2.824, -7.028]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
                <mesh castShadow receiveShadow geometry={nodes.Object_49.geometry} material={materials['Material.005']} position={[-1.044, 2.824, -7.028]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
                <mesh castShadow receiveShadow geometry={nodes.Object_51.geometry} material={materials['Material.005']} position={[-1.044, 3.043, -7.028]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            </group>


            <mesh castShadow receiveShadow geometry={nodes.Object_53.geometry} material={materials['Material.005']} position={[4.972, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />


//MOZDA ovaj pesak
            <mesh castShadow receiveShadow geometry={nodes.Object_55.geometry} material={materials['Material.005']} position={[2.966, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />




            <group ref={blackKingsPawnRef}>
                <mesh castShadow receiveShadow geometry={nodes.Object_57.geometry} material={materials['Material.005']} position={[0.96, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            </group>


            <mesh castShadow receiveShadow geometry={nodes.Object_59.geometry} material={materials['Material.005']} position={[-1.045, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_61.geometry} material={materials['Material.005']} position={[-3.051, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_63.geometry} material={materials['Material.005']} position={[-5.057, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_65.geometry} material={materials['Material.005']} position={[-7.062, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_67.geometry} material={materials['Material.005']} position={[-7.077, 1.1, -7.052]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_69.geometry} material={materials['Material.005']} position={[6.982, 1.135, -7.052]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_13.geometry} material={materials['Material.005']} position={[6.978, 1.034, -5.147]} rotation={[Math.PI, 0, Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_15.geometry} material={materials.Chess_White} position={[0.952, 2.177, 6.956]} rotation={[0, 0, -Math.PI / 2]} scale={0.224} />
            <mesh castShadow receiveShadow geometry={nodes.Object_19.geometry} material={materials['Material.005']} position={[0.952, 2.177, -6.857]} rotation={[0, 0, -Math.PI / 2]} scale={0.224} />
            <mesh castShadow receiveShadow geometry={nodes.Object_79.geometry} material={materials.Chess_White} position={[-4.903, 1.504, 7.019]} rotation={[Math.PI / 2, 0, 0]} scale={1.3} />


            //crni konji
            <mesh castShadow receiveShadow geometry={nodes.Object_81.geometry} material={materials['Material.005']} position={[-4.903, 1.504, -6.997]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.3} />
            <mesh castShadow receiveShadow geometry={nodes.Object_83.geometry} material={materials['Material.005']} position={[-4.903, 1.504, -6.997]} rotation={[Math.PI / 2, 0, Math.PI]} scale={1.3} />






            <mesh castShadow receiveShadow geometry={nodes.Object_77.geometry} material={materials.Chess_White} position={[4.903, 1.504, 7.019]} rotation={[Math.PI / 2, 0, 0]} scale={1.3} />




            <group ref={whiteQueenRef2}>
                <group ref={whiteQueenRef}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_17.geometry} material={materials.Chess_White} position={[-0.994, 1.978, 6.92]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
                </group>
            </group>




            <mesh castShadow receiveShadow geometry={nodes.Object_71.geometry} material={materials.Chess_White} position={[2.917, 1.483, 6.941]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />




            <group ref={whiteBishopRef2}>
                <group ref={whiteBishopRef}>
                    <mesh castShadow receiveShadow geometry={nodes.Object_21.geometry} material={materials.Chess_White} position={[-3.006, 1.483, 6.941]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
                </group>
            </group>


            <mesh castShadow receiveShadow geometry={nodes.Object_23.geometry} material={materials.Chess_White} position={[-7.07, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_25.geometry} material={materials.Chess_White} position={[-5.065, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />



            <group ref={whiteBishopsPawnRef}>
                <mesh castShadow receiveShadow geometry={nodes.Object_27.geometry} material={materials.Chess_White} position={[-3.059, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            </group>




            <group ref={whiteQueensPawnRef}>
                <mesh castShadow receiveShadow geometry={nodes.Object_29.geometry} material={materials.Chess_White} position={[-1.053, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            </group>




            <mesh castShadow receiveShadow geometry={nodes.Object_31.geometry} material={materials.Chess_White} position={[2.958, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_33.geometry} material={materials.Chess_White} position={[4.964, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_35.geometry} material={materials.Chess_White} position={[6.97, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_37.geometry} material={materials.Chess_White} position={[6.984, 1.1, 6.944]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
            <mesh castShadow receiveShadow geometry={nodes.Object_39.geometry} material={materials.Chess_White} position={[-7.075, 1.135, 6.944]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />


            <mesh castShadow receiveShadow geometry={nodes.Object_73.geometry} material={materials['Material.005']} position={[-3.006, 1.483, -6.988]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />



            <group ref={blackBishopRef4}>
                <group ref={blackBishopRef3}>
                    <group ref={blackBishopRef2}>
                        <group ref={blackBishopRef}>
                            <mesh castShadow receiveShadow geometry={nodes.Object_75.geometry} material={materials['Material.005']} position={[2.917, 1.483, -6.988]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
                        </group>
                    </group>
                </group>
            </group>

            <mesh castShadow receiveShadow geometry={nodes.Object_4.geometry} material={materials.Chess_White} position={[0.953, 1.034, 5.039]} rotation={[0, 0, -Math.PI / 2]} scale={0.151} />
        </group>
    )
}

useGLTF.preload('/models/chess.glb')
