/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/ship.glb 
*/

import React from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Ship(props) {
    const group = React.useRef()
    const { nodes, materials, animations } = useGLTF('/models/ship.glb')
    const { actions } = useAnimations(animations, group)
    return (
        <group ref={group} {...props} dispose={null}>
            <group name="Scene">
                <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={0.2}>
                    <group name="920757bd054e49399c1221d3a6790373abccleanermaterialmergergles">
                        <group name="Object_2" rotation={[Math.PI / 2, 0, 0]}>
                            <group name="Object_3">
                                <group name="Object_4" position={[-0.103, -7.312, -9.555]} scale={2} />
                                <group name="Object_5" scale={14.764}>
                                    <group name="MorphMainGroup">
                                        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials.Plane} morphTargetDictionary={nodes.Plane.morphTargetDictionary} morphTargetInfluences={nodes.Plane.morphTargetInfluences} />
                                    </group>
                                </group>
                            </group>
                        </group>
                    </group>
                </group>
                <group name="Sketchfab_model001" position={[0.599, 0.362, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.441, 0.442, 0.373]}>
                    <group name="Collada_visual_scene_group" rotation={[Math.PI / 2, 0, 0]}>
                        <group name="g">
                            <mesh name="defaultMaterial" geometry={nodes.defaultMaterial.geometry} material={materials.Standardmaterial} />
                        </group>
                    </group>
                </group>
            </group>
        </group>
    )
}

useGLTF.preload('/models/ship.glb')
