/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/trade.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Trade(props) {
  const { nodes, materials } = useGLTF('/models/trade.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[2.21, -0.034, 0.833]}>
        <mesh geometry={nodes.Object_4.geometry} material={materials['20Ft_Generic_Old']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['20Ft_Generic_Old']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.648, 0]} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['20Ft_Generic_Old']} position={[-0.031, 2.716, 0]} rotation={[Math.PI, -0.561, Math.PI]} />
      </group>
      <group position={[2.21, -0.034, -9.408]}>
        <mesh geometry={nodes.Object_52.geometry} material={materials['20Ft_Generic_Var3']} />
        <mesh geometry={nodes.Object_54.geometry} material={materials['20Ft_Generic_Old']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.871, 0]} />
        <mesh geometry={nodes.Object_56.geometry} material={materials['20Ft_Generic_Var2']} position={[-0.031, 2.716, 0]} rotation={[0, -0.516, 0]} />
      </group>
      <group position={[7.695, 0, 8.498]}>
        <mesh geometry={nodes.Object_58.geometry} material={materials['40Ft_Generic_Var1']} />
        <mesh geometry={nodes.Object_60.geometry} material={materials['40Ft_Generic_Var1']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.195, 0]} />
        <mesh geometry={nodes.Object_62.geometry} material={materials['40Ft_Generic_Var1']} position={[-0.031, 2.716, 0]} rotation={[0, -0.57, 0]} />
      </group>
      <group position={[7.695, 0, 11.639]}>
        <mesh geometry={nodes.Object_64.geometry} material={materials['40Ft_Generic_Var2']} />
        <mesh geometry={nodes.Object_66.geometry} material={materials['40Ft_Generic_Var2']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.491, 0]} />
        <mesh geometry={nodes.Object_68.geometry} material={materials['40Ft_Generic_Var2']} position={[-0.031, 2.716, 0]} rotation={[0, -0.57, 0]} />
      </group>
      <group position={[7.695, 0, 24.579]}>
        <mesh geometry={nodes.Object_10.geometry} material={materials['40Ft_Var1']} />
        <mesh geometry={nodes.Object_12.geometry} material={materials['40Ft_Var1']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.828, 0]} />
        <mesh geometry={nodes.Object_14.geometry} material={materials['40Ft_Var1']} position={[-0.031, 2.716, 0]} rotation={[0, -0.44, 0]} />
      </group>
      <group position={[7.695, 0, 21.325]}>
        <mesh geometry={nodes.Object_16.geometry} material={materials['40Ft_Var2']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials['40Ft_Var2']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.453, 0]} />
        <mesh geometry={nodes.Object_20.geometry} material={materials['40Ft_Var2']} position={[-0.031, 2.716, 0]} />
      </group>
      <group position={[7.695, 0, 18.136]}>
        <mesh geometry={nodes.Object_22.geometry} material={materials['40Ft_Var3']} />
        <mesh geometry={nodes.Object_24.geometry} material={materials['40Ft_Var3']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.586, 0]} />
        <mesh geometry={nodes.Object_26.geometry} material={materials['40Ft_Var3']} position={[-0.031, 2.716, 0]} rotation={[0, -0.403, 0]} />
      </group>
      <group position={[2.21, 0, 4.092]}>
        <mesh geometry={nodes.Object_28.geometry} material={materials['20Ft_Var1']} />
        <mesh geometry={nodes.Object_30.geometry} material={materials['20Ft_Var1']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.467, 0]} />
        <mesh geometry={nodes.Object_32.geometry} material={materials['20Ft_Var1']} position={[-0.031, 2.716, 0]} />
      </group>
      <group position={[7.695, 0, 27.906]}>
        <mesh geometry={nodes.Object_34.geometry} material={materials['40Ft_Generic_Clean']} />
        <mesh geometry={nodes.Object_36.geometry} material={materials['40Ft_Generic_Clean']} position={[-0.031, 2.716, -2.416]} rotation={[0, 1.277, 0]} />
        <mesh geometry={nodes.Object_38.geometry} material={materials['40Ft_Generic_Clean']} position={[-0.031, 2.716, 0]} rotation={[0, -0.571, 0]} />
      </group>
      <group position={[7.695, 0, 14.837]}>
        <mesh geometry={nodes.Object_70.geometry} material={materials['40Ft_Generic_Var3']} />
        <mesh geometry={nodes.Object_72.geometry} material={materials['40Ft_Generic_Var3']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.559, 0]} />
        <mesh geometry={nodes.Object_74.geometry} material={materials['40Ft_Generic_Var3']} position={[-0.031, 2.716, 0]} rotation={[0, -0.51, 0]} />
      </group>
      <group position={[2.21, -0.034, -2.57]}>
        <mesh geometry={nodes.Object_40.geometry} material={materials['20Ft_Generic_Var1']} />
        <mesh geometry={nodes.Object_42.geometry} material={materials['20Ft_Generic_Var1']} position={[-0.031, 2.716, -2.416]} rotation={[-Math.PI, 1.362, -Math.PI]} />
        <mesh geometry={nodes.Object_44.geometry} material={materials['20Ft_Generic_Var1']} position={[-0.031, 2.716, 0]} rotation={[Math.PI, -1.496, Math.PI]} />
      </group>
      <group position={[2.21, -0.034, -6.054]}>
        <mesh geometry={nodes.Object_46.geometry} material={materials['20Ft_Generic_Var2']} />
        <mesh geometry={nodes.Object_48.geometry} material={materials['20Ft_Generic_Var2']} position={[-0.031, 2.716, -2.416]} rotation={[-Math.PI, 1.485, -Math.PI]} />
        <mesh geometry={nodes.Object_50.geometry} material={materials['20Ft_Generic_Var2']} position={[-0.031, 2.716, 0]} rotation={[0, -0.975, 0]} />
      </group>
      <group position={[7.695, 0, 31.305]}>
        <mesh geometry={nodes.Object_120.geometry} material={materials['40Ft_Generic_old']} />
        <mesh geometry={nodes.Object_122.geometry} material={materials['40Ft_Generic_old']} position={[-0.031, 2.716, -2.416]} rotation={[0, 0.559, 0]} />
        <mesh geometry={nodes.Object_124.geometry} material={materials['40Ft_Generic_old']} position={[-0.031, 2.716, 0]} rotation={[0, -0.51, 0]} />
      </group>
      <mesh geometry={nodes.Object_94.geometry} material={materials['20Ft_Generic_Var1']} position={[-6.245, 0, 2.157]} />
      <mesh geometry={nodes.Object_96.geometry} material={materials['20Ft_Generic_Var2']} position={[-6.245, 0, -0.259]} />
      <mesh geometry={nodes.Object_98.geometry} material={materials['20Ft_Generic_Var3']} position={[-6.245, 0, -2.676]} />
      <mesh geometry={nodes.Object_76.geometry} material={materials['40Ft_Var1']} position={[-6.245, 0, 24.298]} />
      <mesh geometry={nodes.Object_84.geometry} material={materials['40Ft_Var3']} position={[-8.827, 0, 19.465]} />
      <mesh geometry={nodes.Object_86.geometry} material={materials['40Ft_Generic_Var3']} position={[-6.245, 0, 17.049]} />
      <mesh geometry={nodes.Object_78.geometry} material={materials['40Ft_Var2']} position={[-6.245, 0, 21.881]} />
      <mesh geometry={nodes.Object_88.geometry} material={materials['40Ft_Generic_Var2']} position={[-6.245, 0, 14.633]} />
      <mesh geometry={nodes.Object_90.geometry} material={materials['40Ft_Generic_Var1']} position={[-6.245, 0, 12.217]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials['20Ft_Generic_Old']} position={[-6.245, 0, 4.573]} />
      <mesh geometry={nodes.Object_100.geometry} material={materials['40Ft_Var1']} position={[-6.245, 2.924, 21.881]} />
      <mesh geometry={nodes.Object_102.geometry} material={materials['40Ft_Var2']} position={[-8.827, 2.924, 19.465]} />
      <mesh geometry={nodes.Object_104.geometry} material={materials['40Ft_Generic_Clean']} position={[-6.245, 2.924, 24.298]} />
      <mesh geometry={nodes.Object_106.geometry} material={materials['40Ft_Var3']} position={[-6.245, 2.924, 17.049]} />
      <mesh geometry={nodes.Object_80.geometry} material={materials['20Ft_Var1']} position={[-6.245, 0, 6.989]} />
      <mesh geometry={nodes.Object_82.geometry} material={materials['40Ft_Generic_Clean']} position={[-6.245, 0, 26.714]} />
      <mesh geometry={nodes.Object_110.geometry} material={materials['20Ft_Generic_Old']} position={[-6.245, 2.924, 6.989]} />
      <mesh geometry={nodes.Object_112.geometry} material={materials['20Ft_Generic_Old']} position={[-6.245, 2.924, 4.573]} />
      <mesh geometry={nodes.Object_108.geometry} material={materials['40Ft_Generic_Var1']} position={[-6.245, 2.924, 26.714]} />
      <mesh geometry={nodes.Object_114.geometry} material={materials['20Ft_Generic_Var2']} position={[-6.245, 2.924, 2.157]} />
      <mesh geometry={nodes.Object_116.geometry} material={materials['20Ft_Var1']} position={[-6.245, 5.848, 6.989]} />
      <mesh geometry={nodes.Object_118.geometry} material={materials['20Ft_Var1']} position={[-6.245, 5.848, 4.573]} />
      <mesh geometry={nodes.Object_126.geometry} material={materials['40Ft_Var1']} position={[-6.245, 5.848, 26.714]} />
      <mesh geometry={nodes.Object_128.geometry} material={materials['40Ft_Var3']} position={[-6.245, 5.848, 21.881]} />
    </group>
  )
}

useGLTF.preload('/models/trade.glb')
