/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/galleon.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Galleon(props) {
    const { nodes, materials } = useGLTF('/models/galleon.glb')
    return (
        <group {...props} dispose={null}>
            <group position={[0, 3.72, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={4.689}>
                <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Standardmaterial} rotation={[Math.PI / 2, 0, 0]} />
            </group>
        </group>
    )
}

useGLTF.preload('/models/galleon.glb')
