import { Courier_Prime } from "next/font/google";
import "./globals.css";
import { MainCanvas } from "@/components/three/mainCanvas";
import { SmoothScrolling } from "@/components/SmoothScrolling";

const courierPrime = Courier_Prime({
  variable: "--font-courier-prime",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${courierPrime.variable} antialiased max-w-[100vw] overflow-x-hidden`}
      >
        <SmoothScrolling>
          {children}
        </SmoothScrolling>
        <MainCanvas />
      </body>
    </html>
  );
}
